### PR TITLE
Improve README

### PR DESCRIPTION
**Pull request by nokeya**
- Added example of static build command
- Fixed `loadFromFile`/`loadFormData`
- Trimmed some trailing whitespaces

### CODE REVIEW

**Comment by fire** [comment]
What does rlottie style guide say about auto?

**Comment by nokeya** [comment]
> 
> 
> What does rlottie style guide say about auto?

Search says 45 occurrences, so it seems to be ok with it?

**Comment by smohantty** [comment]
@nokeya ,
The patch looks good. but looks like it has 3 commits . could you please rebase your repo with latest rlottie.

**Comment by nokeya** [comment]
done

**Comment by smohantty** [comment]
thanks

**Pull request merged**
